#!/bin/bash

set -e

echo "removing the web folder from all books"

rm -rf books/6-muruga-temple-pilgrimage_ei/web
rm -rf books/12-beliefs-of-saivism_ei/web
rm -rf books/aging-gracefully_ei/web
rm -rf books/ahimsa-to-do-no-harm_ei/web
rm -rf books/all-about-kauai-hindu-monastery/web
rm -rf books/amoroso-ganesha_es/web
rm -rf books/andre-test-book/web
rm -rf books/anger-management_ei/web
rm -rf books/approaching-god_ei/web
rm -rf books/a-creed-of-monasticism_ei/web
rm -rf books/cancao-do-sannyasin/web
rm -rf books/character-building-workbook/web
rm -rf books/code-of-conduct_ei/web
rm -rf books/commencer-a-mediter_fr/web
rm -rf books/como-volverse-un-hindu_es/web
rm -rf books/cultural-cues-and-clues_ei/web
rm -rf books/dancing-with-siva/web
rm -rf books/danzando-con-siva_es/web
rm -rf books/death-and-dying_ei/web
rm -rf books/der-selbstgott_de/web
rm -rf books/dez-questoes-acerca-do-hinduismo_pt/web
rm -rf books/difference-is-real_ei/web
rm -rf books/fabric-begets-fashion_ei/web
rm -rf books/family-life-monastic-life_ei/web
rm -rf books/fine-art-of-meditation_ei/web
rm -rf books/five-powers-of-siva_ei/web
rm -rf books/fourteen-questions_ei/web
rm -rf books/four-denominations-of-hinduism_ei/web
rm -rf books/god-and-gods-of-hinduism/web
rm -rf books/god-soul-world_ei/web
rm -rf books/growing-up-hindu/web
rm -rf books/growing-up-hindu_ei/web
rm -rf books/gurudevas-1993-address-to-the-tamils-in-europe_ta/web
rm -rf books/gurudevas-spiritual-visions/web
rm -rf books/gurudevas-toolbox/web
rm -rf books/gurudevas-werkzeugkasten_de/web
rm -rf books/guru-purnima_pt/web
rm -rf books/hail-hindu-heroes_ei/web
rm -rf books/health-and-healing/web
rm -rf books/hinduisma-agama-terunggul-di-dunia_ms/web
rm -rf books/hinduisms-nandinatha-sutras/web
rm -rf books/hinduism-and-buddhism_ei/web
rm -rf books/hinduism-the-greatest-religion-in-the-world_ei/web
rm -rf books/hinduistischer-verhaltenscode_de/web
rm -rf books/hindu-astrologys-lunar-mansions_ei/web
rm -rf books/hindu-basics/web
rm -rf books/hindu-children-modern-stories_ei/web
rm -rf books/hindu-christian-point-counterpoint/web
rm -rf books/hindu-history-chapter-five/web
rm -rf books/hindu-history-chapter-four/web
rm -rf books/hindu-history-chapter-one/web
rm -rf books/hindu-history-chapter-three/web
rm -rf books/hindu-history-chapter-two/web
rm -rf books/hindu-hospitality_ei/web
rm -rf books/hindu-primer_ei/web
rm -rf books/hindu-scriptures_ei/web
rm -rf books/hindu-wedding_ei/web
rm -rf books/holy-festivals_ei/web
rm -rf books/holy-orders-of-sannyas/web
rm -rf books/home-festivals_ei/web
rm -rf books/home-puja_ei/web
rm -rf books/honoring-the-arts-of-homemaking_ei/web
rm -rf books/honoring-the-spirit-of-community_ei/web
rm -rf books/how-the-major-religions-view-god_ei/web
rm -rf books/how-to-become-a-hindu/web
rm -rf books/how-to-ease-karma_ei/web
rm -rf books/how-to-win-an-argument-with-a-meateater_hu/web
rm -rf books/humanities-diverse-faiths_ei/web
rm -rf books/il-se-dio_it/web
rm -rf books/jyotisha-hindu-astrology_ei/web
rm -rf books/karma-and-reincarnation/web
rm -rf books/karma-management_ei/web
rm -rf books/karma-reincarnation-vivekananda_ei/web
rm -rf books/karma-yoga_ei/web
rm -rf books/kauais-hindu-monastery-of-america_ta/web
rm -rf books/know-thyself_ei/web
rm -rf books/kumbha-mela_ei/web
rm -rf books/largent-de-dieu_fr/web
rm -rf books/lemurian-scrolls/web
rm -rf books/le-catechisme-hindou-sivaite_fr/web
rm -rf books/life-after-death_ei/web
rm -rf books/life-skills-for-hindu-teens/web
rm -rf books/living-with-siva/web
rm -rf books/los-upanishads_es/web
rm -rf books/love-of-god-is-vedanta_ei/web
rm -rf books/loving-ganesha/web
rm -rf books/mantra-yoga_ei/web
rm -rf books/medical-ethics_ei/web
rm -rf books/merging-with-siva/web
rm -rf books/merging-with-siva_ru/web
rm -rf books/modern-matchmaking_ei/web
rm -rf books/monks-cookbook/web
rm -rf books/my-friend-lord-ganesha_ei/web
rm -rf books/nandinatha-sutras_ta/web
rm -rf books/nove-crencas-do-hinduismo_pt/web
rm -rf books/our-sacred-earth_ei/web
rm -rf books/our-subtle-energy-highway_ei/web
rm -rf books/pancha-ganapati/web
rm -rf books/parenting-with-love_ei/web
rm -rf books/path-to-siva/web
rm -rf books/raising-children-as-good-hindus_ei/web
rm -rf books/rites-of-passage_ei/web
rm -rf books/sacred-pilgrimage_ei/web
rm -rf books/sacred-symbols_ei/web
rm -rf books/sadhana-guide-for-pilgrims/web
rm -rf books/sadhana_ei/web
rm -rf books/saiva-dharma-shastras/web
rm -rf books/saivite-hindu-religion-book-four/web
rm -rf books/saivite-hindu-religion-book-one/web
rm -rf books/saivite-hindu-religion-book-three/web
rm -rf books/saivite-hindu-religion-book-two/web
rm -rf books/saivite-virtue/web
rm -rf books/secrets-of-indian-gastronomy_ei/web
rm -rf books/self-and-samadhi/web
rm -rf books/silence-is-golden_ei/web
rm -rf books/stoppt-den-krieg-zu-hause_de/web
rm -rf books/sutras-in-tamil_ta/web
rm -rf books/ten-questions-and-answers-in-tamil_ta/web
rm -rf books/ten-tales-about-religious-life/web
rm -rf books/ten-tales-about-self-control/web
rm -rf books/testament-of-truth/web
rm -rf books/the-chakras_ei/web
rm -rf books/the-five-states-of-mind_ei/web
rm -rf books/the-guru-chronicles/web
rm -rf books/the-history-of-hindu-india/web
rm -rf books/the-home-shrine_ei/web
rm -rf books/the-human-aura_ei/web
rm -rf books/the-meat-free-life_ei/web
rm -rf books/the-mystic-mind-and-music-of-kabir_ei/web
rm -rf books/the-power-of-affirmation_ei/web
rm -rf books/the-satguru_ei/web
rm -rf books/the-songs-of-tayumanavar/web
rm -rf books/tirukural/web
rm -rf books/tirumantiram/web
rm -rf books/twelve-shum-meditations/web
rm -rf books/uniendose-a-siva_es/web
rm -rf books/vedic-experience/web
rm -rf books/verschmelzung-mit-siva_de/web
rm -rf books/visiting-a-hindu-temple_ei/web
rm -rf books/viviendo-con-siva_es/web
rm -rf books/weavers-wisdom/web
rm -rf books/what-is-hinduism/web
rm -rf books/who-is-a-hindu_ei/web
rm -rf books/words-of-our-master/web
rm -rf books/yogaswami_ei/web
rm -rf books/yogas-forgotten-foundation/web
rm -rf books/yoga-primer_ei/web
