#!/bin/bash 
set -e 

echo "will take a while, rest..."

node index.js 6-muruga-temple-pilgrimage_ei
node index.js 12-beliefs-of-saivism_ei
node index.js aging-gracefully_ei
node index.js ahimsa-to-do-no-harm_ei
node index.js all-about-kauai-hindu-monastery
node index.js amoroso-ganesha_es
node index.js anger-management_ei
node index.js approaching-god_ei
node index.js a-creed-of-monasticism_ei
node index.js cancao-do-sannyasin
node index.js character-building-workbook
node index.js code-of-conduct_ei
node index.js commencer-a-mediter_fr
node index.js como-volverse-un-hindu_es
node index.js cultural-cues-and-clues_ei
node index.js dancing-with-siva
node index.js danzando-con-siva_es
node index.js death-and-dying_ei
node index.js der-selbstgott_de
node index.js dez-questoes-acerca-do-hinduismo_pt
node index.js difference-is-real_ei
node index.js fabric-begets-fashion_ei
node index.js family-life-monastic-life_ei
node index.js fine-art-of-meditation_ei
node index.js five-powers-of-siva_ei
node index.js fourteen-questions_ei
node index.js four-denominations-of-hinduism_ei
node index.js god-and-gods-of-hinduism
node index.js god-soul-world_ei
node index.js growing-up-hindu
node index.js growing-up-hindu_ei
node index.js gurudevas-1993-address-to-the-tamils-in-europe_ta
node index.js gurudevas-spiritual-visions
node index.js gurudevas-toolbox
node index.js gurudevas-werkzeugkasten_de
node index.js guru-purnima_pt
node index.js hail-hindu-heroes_ei
node index.js health-and-healing
node index.js hinduisma-agama-terunggul-di-dunia_ms
node index.js hinduisms-nandinatha-sutras
node index.js hinduism-and-buddhism_ei
node index.js hinduism-the-greatest-religion-in-the-world_ei
node index.js hinduistischer-verhaltenscode_de
node index.js hindu-astrologys-lunar-mansions_ei
node index.js hindu-basics
node index.js hindu-children-modern-stories_ei
node index.js hindu-christian-point-counterpoint
node index.js hindu-history-chapter-five
node index.js hindu-history-chapter-four
node index.js hindu-history-chapter-one
node index.js hindu-history-chapter-three
node index.js hindu-history-chapter-two
node index.js hindu-hospitality_ei
node index.js hindu-primer_ei
node index.js hindu-scriptures_ei
node index.js hindu-wedding_ei
node index.js holy-festivals_ei
node index.js holy-orders-of-sannyas
node index.js home-festivals_ei
node index.js home-puja_ei
node index.js honoring-the-arts-of-homemaking_ei
node index.js honoring-the-spirit-of-community_ei
node index.js how-the-major-religions-view-god_ei
node index.js how-to-become-a-hindu
node index.js how-to-ease-karma_ei
node index.js how-to-win-an-argument-with-a-meateater_hu
node index.js humanities-diverse-faiths_ei
node index.js il-se-dio_it
node index.js jyotisha-hindu-astrology_ei
node index.js karma-and-reincarnation
node index.js karma-management_ei
node index.js karma-reincarnation-vivekananda_ei
node index.js karma-yoga_ei
node index.js kauais-hindu-monastery-of-america_ta
node index.js know-thyself_ei
node index.js kumbha-mela_ei
node index.js largent-de-dieu_fr
node index.js lemurian-scrolls
node index.js le-catechisme-hindou-sivaite_fr
node index.js life-after-death_ei
node index.js life-skills-for-hindu-teens
node index.js living-with-siva
node index.js los-upanishads_es
node index.js love-of-god-is-vedanta_ei
node index.js loving-ganesha
node index.js mantra-yoga_ei
node index.js medical-ethics_ei
node index.js merging-with-siva
node index.js merging-with-siva_ru
node index.js modern-matchmaking_ei
node index.js monks-cookbook
node index.js my-friend-lord-ganesha_ei
node index.js nandinatha-sutras_ta
node index.js nove-crencas-do-hinduismo_pt
node index.js our-sacred-earth_ei
node index.js our-subtle-energy-highway_ei
node index.js pancha-ganapati
node index.js parenting-with-love_ei
node index.js raising-children-as-good-hindus_ei
node index.js rites-of-passage_ei
node index.js sacred-pilgrimage_ei
node index.js sacred-symbols_ei
node index.js sadhana-guide-for-pilgrims
node index.js sadhana_ei
node index.js saiva-dharma-shastras
node index.js saivite-hindu-religion-book-four
node index.js saivite-hindu-religion-book-one
node index.js saivite-hindu-religion-book-three
node index.js saivite-hindu-religion-book-two
node index.js saivite-virtue
node index.js secrets-of-indian-gastronomy_ei
node index.js self-and-samadhi
node index.js silence-is-golden_ei
node index.js stoppt-den-krieg-zu-hause_de
node index.js sutras-in-tamil_ta
node index.js ten-questions-and-answers-in-tamil_ta
node index.js ten-tales-about-religious-life
node index.js ten-tales-about-self-control
node index.js testament-of-truth
node index.js the-chakras_ei
# node index.js the-five-states-of-mind_ei
node index.js the-guru-chronicles
node index.js the-history-of-hindu-india
node index.js the-home-shrine_ei
node index.js the-human-aura_ei
node index.js the-meat-free-life_ei
node index.js the-mystic-mind-and-music-of-kabir_ei
node index.js the-power-of-affirmation_ei
node index.js the-satguru_ei
node index.js the-songs-of-tayumanavar
node index.js tirukural
node index.js tirumantiram
node index.js twelve-shum-meditations
node index.js uniendose-a-siva_es
node index.js vedic-experience
node index.js verschmelzung-mit-siva_de
node index.js visiting-a-hindu-temple_ei
node index.js viviendo-con-siva_es
node index.js weavers-wisdom
node index.js what-is-hinduism
node index.js who-is-a-hindu_ei
node index.js words-of-our-master
node index.js yogaswami_ei
node index.js yogas-forgotten-foundation
node index.js yoga-primer_ei
