#!/bin/bash
echo 'Uploading all books...'
set -e

rsync -avz books/6-muruga-temple-pilgrimage_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/6-muruga-temple-pilgrimage_ei/
rsync -avz books/12-beliefs-of-saivism_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/12-beliefs-of-saivism_ei/
rsync -avz books/aging-gracefully_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/aging-gracefully_ei/
rsync -avz books/ahimsa-to-do-no-harm_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/ahimsa-to-do-no-harm_ei/
rsync -avz books/all-about-kauai-hindu-monastery/web devhap@dev.himalayanacademy.com:public_html/media/books/all-about-kauai-hindu-monastery/
rsync -avz books/amoroso-ganesha_es/web devhap@dev.himalayanacademy.com:public_html/media/books/amoroso-ganesha_es/
rsync -avz books/anger-management_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/anger-management_ei/
rsync -avz books/approaching-god_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/approaching-god_ei/
rsync -avz books/a-creed-of-monasticism_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/a-creed-of-monasticism_ei/
rsync -avz books/cancao-do-sannyasin/web devhap@dev.himalayanacademy.com:public_html/media/books/cancao-do-sannyasin/
rsync -avz books/character-building-workbook/web devhap@dev.himalayanacademy.com:public_html/media/books/character-building-workbook/
rsync -avz books/code-of-conduct_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/code-of-conduct_ei/
rsync -avz books/commencer-a-mediter_fr/web devhap@dev.himalayanacademy.com:public_html/media/books/commencer-a-mediter_fr/
rsync -avz books/como-volverse-un-hindu_es/web devhap@dev.himalayanacademy.com:public_html/media/books/como-volverse-un-hindu_es/
rsync -avz books/cultural-cues-and-clues_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/cultural-cues-and-clues_ei/
rsync -avz books/dancing-with-siva/web devhap@dev.himalayanacademy.com:public_html/media/books/dancing-with-siva/
rsync -avz books/danzando-con-siva_es/web devhap@dev.himalayanacademy.com:public_html/media/books/danzando-con-siva_es/
rsync -avz books/death-and-dying_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/death-and-dying_ei/
rsync -avz books/der-selbstgott_de/web devhap@dev.himalayanacademy.com:public_html/media/books/der-selbstgott_de/
rsync -avz books/dez-questoes-acerca-do-hinduismo_pt/web devhap@dev.himalayanacademy.com:public_html/media/books/dez-questoes-acerca-do-hinduismo_pt/
rsync -avz books/difference-is-real_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/difference-is-real_ei/
rsync -avz books/fabric-begets-fashion_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/fabric-begets-fashion_ei/
rsync -avz books/family-life-monastic-life_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/family-life-monastic-life_ei/
rsync -avz books/fine-art-of-meditation_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/fine-art-of-meditation_ei/
rsync -avz books/five-powers-of-siva_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/five-powers-of-siva_ei/
rsync -avz books/fourteen-questions_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/fourteen-questions_ei/
rsync -avz books/four-denominations-of-hinduism_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/four-denominations-of-hinduism_ei/
rsync -avz books/god-and-gods-of-hinduism/web devhap@dev.himalayanacademy.com:public_html/media/books/god-and-gods-of-hinduism/
rsync -avz books/god-soul-world_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/god-soul-world_ei/
rsync -avz books/growing-up-hindu/web devhap@dev.himalayanacademy.com:public_html/media/books/growing-up-hindu/
rsync -avz books/growing-up-hindu_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/growing-up-hindu_ei/
rsync -avz books/gurudevas-1993-address-to-the-tamils-in-europe_ta/web devhap@dev.himalayanacademy.com:public_html/media/books/gurudevas-1993-address-to-the-tamils-in-europe_ta/
rsync -avz books/gurudevas-spiritual-visions/web devhap@dev.himalayanacademy.com:public_html/media/books/gurudevas-spiritual-visions/
rsync -avz books/gurudevas-toolbox/web devhap@dev.himalayanacademy.com:public_html/media/books/gurudevas-toolbox/
rsync -avz books/gurudevas-werkzeugkasten_de/web devhap@dev.himalayanacademy.com:public_html/media/books/gurudevas-werkzeugkasten_de/
rsync -avz books/guru-purnima_pt/web devhap@dev.himalayanacademy.com:public_html/media/books/guru-purnima_pt/
rsync -avz books/hail-hindu-heroes_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hail-hindu-heroes_ei/
rsync -avz books/health-and-healing/web devhap@dev.himalayanacademy.com:public_html/media/books/health-and-healing/
rsync -avz books/hinduisma-agama-terunggul-di-dunia_ms/web devhap@dev.himalayanacademy.com:public_html/media/books/hinduisma-agama-terunggul-di-dunia_ms/
rsync -avz books/hinduisms-nandinatha-sutras/web devhap@dev.himalayanacademy.com:public_html/media/books/hinduisms-nandinatha-sutras/
rsync -avz books/hinduism-and-buddhism_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hinduism-and-buddhism_ei/
rsync -avz books/hinduism-the-greatest-religion-in-the-world_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hinduism-the-greatest-religion-in-the-world_ei/
rsync -avz books/hinduistischer-verhaltenscode_de/web devhap@dev.himalayanacademy.com:public_html/media/books/hinduistischer-verhaltenscode_de/
rsync -avz books/hindu-astrologys-lunar-mansions_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-astrologys-lunar-mansions_ei/
rsync -avz books/hindu-basics/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-basics/
rsync -avz books/hindu-children-modern-stories_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-children-modern-stories_ei/
rsync -avz books/hindu-christian-point-counterpoint/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-christian-point-counterpoint/
rsync -avz books/hindu-history-chapter-five/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-history-chapter-five/
rsync -avz books/hindu-history-chapter-four/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-history-chapter-four/
rsync -avz books/hindu-history-chapter-one/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-history-chapter-one/
rsync -avz books/hindu-history-chapter-three/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-history-chapter-three/
rsync -avz books/hindu-history-chapter-two/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-history-chapter-two/
rsync -avz books/hindu-hospitality_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-hospitality_ei/
rsync -avz books/hindu-primer_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-primer_ei/
rsync -avz books/hindu-scriptures_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-scriptures_ei/
rsync -avz books/hindu-wedding_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/hindu-wedding_ei/
rsync -avz books/holy-festivals_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/holy-festivals_ei/
rsync -avz books/holy-orders-of-sannyas/web devhap@dev.himalayanacademy.com:public_html/media/books/holy-orders-of-sannyas/
rsync -avz books/home-festivals_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/home-festivals_ei/
rsync -avz books/home-puja_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/home-puja_ei/
rsync -avz books/honoring-the-arts-of-homemaking_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/honoring-the-arts-of-homemaking_ei/
rsync -avz books/honoring-the-spirit-of-community_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/honoring-the-spirit-of-community_ei/
rsync -avz books/how-the-major-religions-view-god_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/how-the-major-religions-view-god_ei/
rsync -avz books/how-to-become-a-hindu/web devhap@dev.himalayanacademy.com:public_html/media/books/how-to-become-a-hindu/
rsync -avz books/how-to-ease-karma_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/how-to-ease-karma_ei/
rsync -avz books/how-to-win-an-argument-with-a-meateater_hu/web devhap@dev.himalayanacademy.com:public_html/media/books/how-to-win-an-argument-with-a-meateater_hu/
rsync -avz books/humanities-diverse-faiths_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/humanities-diverse-faiths_ei/
rsync -avz books/il-se-dio_it/web devhap@dev.himalayanacademy.com:public_html/media/books/il-se-dio_it/
rsync -avz books/jyotisha-hindu-astrology_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/jyotisha-hindu-astrology_ei/
rsync -avz books/karma-and-reincarnation/web devhap@dev.himalayanacademy.com:public_html/media/books/karma-and-reincarnation/
rsync -avz books/karma-management_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/karma-management_ei/
rsync -avz books/karma-reincarnation-vivekananda_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/karma-reincarnation-vivekananda_ei/
rsync -avz books/karma-yoga_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/karma-yoga_ei/
rsync -avz books/kauais-hindu-monastery-of-america_ta/web devhap@dev.himalayanacademy.com:public_html/media/books/kauais-hindu-monastery-of-america_ta/
rsync -avz books/know-thyself_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/know-thyself_ei/
rsync -avz books/kumbha-mela_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/kumbha-mela_ei/
rsync -avz books/largent-de-dieu_fr/web devhap@dev.himalayanacademy.com:public_html/media/books/largent-de-dieu_fr/
rsync -avz books/lemurian-scrolls/web devhap@dev.himalayanacademy.com:public_html/media/books/lemurian-scrolls/
rsync -avz books/le-catechisme-hindou-sivaite_fr/web devhap@dev.himalayanacademy.com:public_html/media/books/le-catechisme-hindou-sivaite_fr/
rsync -avz books/life-after-death_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/life-after-death_ei/
rsync -avz books/life-skills-for-hindu-teens/web devhap@dev.himalayanacademy.com:public_html/media/books/life-skills-for-hindu-teens/
rsync -avz books/living-with-siva/web devhap@dev.himalayanacademy.com:public_html/media/books/living-with-siva/
rsync -avz books/los-upanishads_es/web devhap@dev.himalayanacademy.com:public_html/media/books/los-upanishads_es/
rsync -avz books/love-of-god-is-vedanta_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/love-of-god-is-vedanta_ei/
rsync -avz books/loving-ganesha/web devhap@dev.himalayanacademy.com:public_html/media/books/loving-ganesha/
rsync -avz books/mantra-yoga_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/mantra-yoga_ei/
rsync -avz books/medical-ethics_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/medical-ethics_ei/
rsync -avz books/merging-with-siva/web devhap@dev.himalayanacademy.com:public_html/media/books/merging-with-siva/
rsync -avz books/merging-with-siva_ru/web devhap@dev.himalayanacademy.com:public_html/media/books/merging-with-siva_ru/
rsync -avz books/modern-matchmaking_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/modern-matchmaking_ei/
rsync -avz books/monks-cookbook/web devhap@dev.himalayanacademy.com:public_html/media/books/monks-cookbook/
rsync -avz books/my-friend-lord-ganesha_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/my-friend-lord-ganesha_ei/
rsync -avz books/nandinatha-sutras_ta/web devhap@dev.himalayanacademy.com:public_html/media/books/nandinatha-sutras_ta/
rsync -avz books/nove-crencas-do-hinduismo_pt/web devhap@dev.himalayanacademy.com:public_html/media/books/nove-crencas-do-hinduismo_pt/
rsync -avz books/our-sacred-earth_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/our-sacred-earth_ei/
rsync -avz books/our-subtle-energy-highway_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/our-subtle-energy-highway_ei/
rsync -avz books/pancha-ganapati/web devhap@dev.himalayanacademy.com:public_html/media/books/pancha-ganapati/
rsync -avz books/parenting-with-love_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/parenting-with-love_ei/
rsync -avz books/path-to-siva/web devhap@dev.himalayanacademy.com:public_html/media/books/path-to-siva/
rsync -avz books/raising-children-as-good-hindus_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/raising-children-as-good-hindus_ei/
rsync -avz books/rites-of-passage_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/rites-of-passage_ei/
rsync -avz books/sacred-pilgrimage_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/sacred-pilgrimage_ei/
rsync -avz books/sacred-symbols_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/sacred-symbols_ei/
rsync -avz books/sadhana-guide-for-pilgrims/web devhap@dev.himalayanacademy.com:public_html/media/books/sadhana-guide-for-pilgrims/
rsync -avz books/sadhana_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/sadhana_ei/
rsync -avz books/saiva-dharma-shastras/web devhap@dev.himalayanacademy.com:public_html/media/books/saiva-dharma-shastras/
rsync -avz books/saivite-hindu-religion-book-four/web devhap@dev.himalayanacademy.com:public_html/media/books/saivite-hindu-religion-book-four/
rsync -avz books/saivite-hindu-religion-book-one/web devhap@dev.himalayanacademy.com:public_html/media/books/saivite-hindu-religion-book-one/
rsync -avz books/saivite-hindu-religion-book-three/web devhap@dev.himalayanacademy.com:public_html/media/books/saivite-hindu-religion-book-three/
rsync -avz books/saivite-hindu-religion-book-two/web devhap@dev.himalayanacademy.com:public_html/media/books/saivite-hindu-religion-book-two/
rsync -avz books/saivite-virtue/web devhap@dev.himalayanacademy.com:public_html/media/books/saivite-virtue/
rsync -avz books/secrets-of-indian-gastronomy_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/secrets-of-indian-gastronomy_ei/
rsync -avz books/self-and-samadhi/web devhap@dev.himalayanacademy.com:public_html/media/books/self-and-samadhi/
rsync -avz books/silence-is-golden_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/silence-is-golden_ei/
rsync -avz books/stoppt-den-krieg-zu-hause_de/web devhap@dev.himalayanacademy.com:public_html/media/books/stoppt-den-krieg-zu-hause_de/
rsync -avz books/sutras-in-tamil_ta/web devhap@dev.himalayanacademy.com:public_html/media/books/sutras-in-tamil_ta/
rsync -avz books/ten-questions-and-answers-in-tamil_ta/web devhap@dev.himalayanacademy.com:public_html/media/books/ten-questions-and-answers-in-tamil_ta/
rsync -avz books/ten-tales-about-religious-life/web devhap@dev.himalayanacademy.com:public_html/media/books/ten-tales-about-religious-life/
rsync -avz books/ten-tales-about-self-control/web devhap@dev.himalayanacademy.com:public_html/media/books/ten-tales-about-self-control/
rsync -avz books/testament-of-truth/web devhap@dev.himalayanacademy.com:public_html/media/books/testament-of-truth/
rsync -avz books/the-chakras_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-chakras_ei/
# rsync -avz books/the-five-states-of-mind_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-five-states-of-mind_ei/
rsync -avz books/the-guru-chronicles/web devhap@dev.himalayanacademy.com:public_html/media/books/the-guru-chronicles/
rsync -avz books/the-history-of-hindu-india/web devhap@dev.himalayanacademy.com:public_html/media/books/the-history-of-hindu-india/
rsync -avz books/the-home-shrine_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-home-shrine_ei/
rsync -avz books/the-human-aura_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-human-aura_ei/
rsync -avz books/the-meat-free-life_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-meat-free-life_ei/
rsync -avz books/the-mystic-mind-and-music-of-kabir_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-mystic-mind-and-music-of-kabir_ei/
rsync -avz books/the-power-of-affirmation_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-power-of-affirmation_ei/
rsync -avz books/the-satguru_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/the-satguru_ei/
rsync -avz books/the-songs-of-tayumanavar/web devhap@dev.himalayanacademy.com:public_html/media/books/the-songs-of-tayumanavar/
rsync -avz books/tirukural/web devhap@dev.himalayanacademy.com:public_html/media/books/tirukural/
rsync -avz books/tirumantiram/web devhap@dev.himalayanacademy.com:public_html/media/books/tirumantiram/
rsync -avz books/twelve-shum-meditations/web devhap@dev.himalayanacademy.com:public_html/media/books/twelve-shum-meditations/
rsync -avz books/uniendose-a-siva_es/web devhap@dev.himalayanacademy.com:public_html/media/books/uniendose-a-siva_es/
rsync -avz books/vedic-experience/web devhap@dev.himalayanacademy.com:public_html/media/books/vedic-experience/
rsync -avz books/verschmelzung-mit-siva_de/web devhap@dev.himalayanacademy.com:public_html/media/books/verschmelzung-mit-siva_de/
rsync -avz books/visiting-a-hindu-temple_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/visiting-a-hindu-temple_ei/
rsync -avz books/viviendo-con-siva_es/web devhap@dev.himalayanacademy.com:public_html/media/books/viviendo-con-siva_es/
rsync -avz books/weavers-wisdom/web devhap@dev.himalayanacademy.com:public_html/media/books/weavers-wisdom/
rsync -avz books/what-is-hinduism/web devhap@dev.himalayanacademy.com:public_html/media/books/what-is-hinduism/
rsync -avz books/who-is-a-hindu_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/who-is-a-hindu_ei/
rsync -avz books/words-of-our-master/web devhap@dev.himalayanacademy.com:public_html/media/books/words-of-our-master/
rsync -avz books/yogaswami_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/yogaswami_ei/
rsync -avz books/yogas-forgotten-foundation/web devhap@dev.himalayanacademy.com:public_html/media/books/yogas-forgotten-foundation/
rsync -avz books/yoga-primer_ei/web devhap@dev.himalayanacademy.com:public_html/media/books/yoga-primer_ei/
